### PR TITLE
Bookstore: Use Redux in React components.

### PR DESCRIPTION
**Pull request by StevenWafeek**
In this project we :
- Use store, actions, and reducers in React.
- Dispatch actions using useDispatch
- Create an initialState variable for your booksSlice
- Display your books, received from the slice, in a reusable component

### CODE REVIEW

**Review by shella12 — CHANGES_REQUESTED** [review]
Hi @StevenWafeek, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- `initialState` has been added to the `booksSlice` ✅ 
- Redux `store` has been passed into the `<Provider>` ✅   

## Required Changes ♻️

Screenshot 2023-06-13 at 11 32 03 AM

- [ ] Please make sure that the `books` are accessed from inside the `<BookList>` with `useSelector` instead of using `useState`. Example snippet:

```jsx

import React from 'react'
import { useSelector } from 'react-redux

function BookList() {
    const books = useSelector((state) => state.books.books)

    return (
        <div>{/* Booklist JSX */}</div>
    )
}

export default BookList

```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by StevenWafeek** [comment]
@shella12 thank you for your feedback, I really appreciate it, but sorry for asking. I can't find the part that I need to useSelector  but i already use access in the booklist and bookform js , can you explain it to me more, please? thank you

**Comment by shella12** [comment]
> @shella12 thank you for your feedback, I really appreciate it, but sorry for asking. I can't find the part that I need to useSelector but i already use access in the booklist and bookform js , can you explain it to me more, please? thank you

Hi @StevenWafeek let me elaborate the suggested changes. So currently what you are doing is creating a new books object instead of fetching the books object from your books reducer. That is why I also have included the example snippet for better understanding of what I meant. 

Please look at your App.js file and see what prop you are passing to bookList component. The books prop you are sending should be fetched from reducer

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @StevenWafeek,

✔️ Use of local state in form component

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
